services:
  robot-tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tests:/opt/robotframework/tests
      - ./resources:/opt/robotframework/resources
      - ./config:/opt/robotframework/config
      - ./results:/opt/robotframework/results
      - ./.env:/opt/robotframework/.env
    env_file:
      - .env
    command: pabot --outputdir /opt/robotframework/results /opt/robotframework/tests